version: '2'
services:
  decentrialized_social-media:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
      - /usr/app/streams
    ports:
      - "3000:3000"
    environment: 
      NODE_ENV: "development"